const button = document.querySelector(".button")
const links = document.querySelector(".links")
const heads = document.querySelector("heads")
const container= document.querySelector(".container")
const nav = document.querySelector("nav")
const firstbody= document.querySelector(".body")
const firstheader= document.querySelector(".first-header")
button.addEventListener("click", ()=>{
    button.classList.toggle("active")
    button.classList.toggle("activ")
    links.classList.toggle("activate")
    container.classList.toggle("activate")
    links.classList.toggle("fixed")
    firstheader.classList.toggle("nav-fixed")
    button.classList.toggle("nav-fixed")
})